### ISSUE TITLE
Get image media from Discord and describe it

### ISSUE THREAD

**Issue by lalalune** [RubyResearch/Agent#14]

**Comment by kawacukennedy** [comment]
Thanks for the detailed review @shaw. Here is our reference implementation addressing both asks:

**1. TEE Verifier Adapters + Unified Proof Format**
We created a reference spec at `sdk/src/tee-verifier.ts` (in our repo) that defines:

- **Unified `AttestationEnvelope`**: `witness` (proof payload) + `binding` (key + optional intent hash) + `signature`
- **TEE-specific proof payloads**: `SgxWitness`, `TdxWitness`, `SevSnpWitness`, `NitroWitness`, `PhalaWitness` — each carrying technology-native fields (mrEnclave, mrSigner, rtmrs, chipId, etc.)
- **`AttestationVerifier<T>` interface**: an abstract adapter your vendor registry can implement per TEE technology. Method: `verify(witness, binding) => VerificationReceipt`
- **`VerifierRegistry`**: register/get/verify routing — a concrete `createVerifierRegistry()` factory
- **`ConfirmationPolicy`** + **`evaluateConfirmation()`**: the gate that checks required technologies, attestation status, and allowed measurement values against the policy

This aligns with your vendor pattern (`TeeVendorInterface`) — a `KubernaVendor` would register its own verifier adapters (e.g., one for Phala/TDX, one for raw SGX quotes) and the registry dispatches based on `witness.technology`.

**2. Confirmation Gate Flow**
The gate evaluates: (a) is attestation required and verified? (b) does `witness.technology` match the required set? (c) do measurements match allowed values? Returns `{ approved, verificationReceipt, rejectionReason }`.

If you want, we can submit a PR that adds `KubernaVendor` implementing `TeeVendorInterface` with these verifier adapters wired into plugin-tee directly. Happy to discuss the exact proof format negotiation — for now the envelope is designed to carry whatever native quote format each TEE produces, with the verifier adapter handling the parsing.

**Comment by kawacukennedy** [comment]
Continuing from the TEE discussion above, here is our cross-chain intents normalization reference:

**ERC-7683 Types** (sdk/src/intent-types.ts):
- `CrossChainOrder`, `ResolvedCrossChainOrder`, `SignedCrossChainOrder`, `FillInstruction`, `FillRequest`, `FillResponse`, `Output`, `OutputReceipt`
- Full type definition matching the ERC-7683 spec (nonce, deadline, swapper, chain IDs, settler addresses, token/amount, fillDeadline, message)

**NEAR Intents Types**:
- `NearIntent`, `SignedNearIntent`, `NearIntentProof`
- Token diff actions with signer, deadline, nonce

**Normalization Layer**:
- `normalizeErc7683()` — maps `CrossChainOrder` → `KubernaNormalizedIntent`
- `normalizeNearIntent()` — maps `NearIntent` → `KubernaNormalizedIntent`
- `normalizeKubernaIntent()` — maps our existing `StructuredIntent` → `KubernaNormalizedIntent`
- `validateIntent()` — validates required fields, positive amounts, non-zero deadlines

**Confirmation Gate Routing**:
- `ConfirmationPolicy` with required confirmations, allowed chains/tokens, max amount, and attestation requirements
- `checkConfirmationPolicy()` — validates an intent against policy before execution

This is exactly what you asked for — a **non-executing normalization/types layer**. It translates between ERC-7683, NEAR Intents, and our Kuberna format without executing anything. The confirmation gate uses it to validate intents before they hit any settlement layer.

We can contribute these type definitions as a `plugin-cross-chain-intents` or a standalone `@elizaos/intent-types` package if that fits your plugin architecture better than a runtime dependency. Thoughts?
